import type { TaxonomyRegistry } from "./types";

export const TAXONOMY_REGISTRY_V1: TaxonomyRegistry = {
  version: "v1.0.0",
  updatedAt: "2026-02-06",
  domains: {
    genre: [
      {
        id: "xuanhuan",
        name: "玄幻",
        aliases: ["东方玄幻", "玄奇修炼"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "xianxia",
        name: "仙侠",
        aliases: ["修仙", "仙侠修真"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "wuxia",
        name: "武侠",
        aliases: ["江湖", "新武侠"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "kehuan",
        name: "科幻",
        aliases: ["硬科幻", "软科幻", "未来科幻"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "qihuan",
        name: "奇幻",
        aliases: ["西方奇幻", "魔幻"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "dushi",
        name: "都市",
        aliases: ["都市异能", "现实都市"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "lishi",
        name: "历史",
        aliases: ["历史架空", "历史传奇"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "junshi",
        name: "军事",
        aliases: ["军事战争", "军旅"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "xuanyi",
        name: "悬疑",
        aliases: ["悬疑推理", "悬疑犯罪"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "kongbu",
        name: "惊悚",
        aliases: ["恐怖", "惊悚恐怖"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "yanqing",
        name: "言情",
        aliases: ["恋爱", "爱情"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "erciyuan",
        name: "二次元",
        aliases: ["同人", "轻小说风"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "wangyou",
        name: "网游",
        aliases: ["游戏网文", "虚拟网游"],
        parentId: "dushi",
        conflicts: [],
        status: "deprecated",
      },
    ],
    trope: [
      {
        id: "system-upgrade",
        name: "系统升级流",
        aliases: ["系统文", "升级流"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "rebirth",
        name: "重生流",
        aliases: ["重生复仇", "重生逆袭"],
        parentId: null,
        conflicts: ["transmigration"],
        status: "active",
      },
      {
        id: "transmigration",
        name: "穿越流",
        aliases: ["魂穿", "身穿", "穿书"],
        parentId: null,
        conflicts: ["rebirth"],
        status: "active",
      },
      {
        id: "academy",
        name: "学院流",
        aliases: ["学院成长", "校园修炼"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "revenge",
        name: "复仇流",
        aliases: ["复仇逆袭", "黑化复仇"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "investigation",
        name: "探案推理流",
        aliases: ["破案", "刑侦流"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "apocalypse",
        name: "末世求生流",
        aliases: ["末日流", "灾变求生"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "business-empire",
        name: "经营商战流",
        aliases: ["商战", "创业经营"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "survival-game",
        name: "无限生存流",
        aliases: ["无限流", "副本流", "规则怪谈"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "farming-slice",
        name: "种田日常流",
        aliases: ["种田文", "慢生活"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "court-politics",
        name: "朝堂权谋流",
        aliases: ["权谋", "宫廷权谋"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "contract-marriage",
        name: "契约婚姻流",
        aliases: ["先婚后爱", "契约恋爱"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "abusive-ceo",
        name: "霸总虐恋流",
        aliases: ["总裁文", "豪门虐恋"],
        parentId: "contract-marriage",
        conflicts: [],
        status: "deprecated",
      },
    ],
    audience: [
      {
        id: "male-oriented",
        name: "男频向",
        aliases: ["男性向", "男生向"],
        parentId: null,
        conflicts: ["female-oriented"],
        status: "active",
      },
      {
        id: "female-oriented",
        name: "女频向",
        aliases: ["女性向", "女生向"],
        parentId: null,
        conflicts: ["male-oriented"],
        status: "active",
      },
      {
        id: "youth",
        name: "青少年向",
        aliases: ["校园向", "少年向"],
        parentId: null,
        conflicts: ["adult-18-plus"],
        status: "active",
      },
      {
        id: "all-ages",
        name: "全年龄向",
        aliases: ["大众向", "家庭向"],
        parentId: null,
        conflicts: ["adult-18-plus"],
        status: "active",
      },
      {
        id: "adult-18-plus",
        name: "18+成人向",
        aliases: ["成人向", "限制级"],
        parentId: null,
        conflicts: ["all-ages", "youth"],
        status: "active",
      },
      {
        id: "light-reading",
        name: "轻阅读向",
        aliases: ["轻松阅读", "碎片化阅读"],
        parentId: null,
        conflicts: ["hardcore-literary"],
        status: "active",
      },
      {
        id: "hardcore-literary",
        name: "硬核文学向",
        aliases: ["严肃文学向", "文艺向"],
        parentId: null,
        conflicts: ["light-reading"],
        status: "active",
      },
      {
        id: "web-serial",
        name: "网文连载向",
        aliases: ["连载向", "平台连载"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "print-market",
        name: "出版向",
        aliases: ["实体出版", "传统出版"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "fandom-community",
        name: "同人社群向",
        aliases: ["圈层向", "同人圈"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "short-video-friendly",
        name: "短视频传播向",
        aliases: ["短视频友好", "切片传播"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "ip-adaptation",
        name: "IP改编受众向",
        aliases: ["影视改编向", "动漫改编向"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
    ],
    emotion: [
      {
        id: "hot-blooded",
        name: "热血爽燃",
        aliases: ["热血", "爽燃"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "healing-warm",
        name: "治愈温暖",
        aliases: ["治愈", "温馨"],
        parentId: null,
        conflicts: ["dark-depressive"],
        status: "active",
      },
      {
        id: "dark-depressive",
        name: "压抑黑暗",
        aliases: ["黑暗", "压抑"],
        parentId: null,
        conflicts: ["healing-warm"],
        status: "active",
      },
      {
        id: "suspense-tense",
        name: "悬疑紧张",
        aliases: ["紧张感", "高压悬疑"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "comedy-light",
        name: "搞笑轻松",
        aliases: ["轻喜剧", "沙雕欢乐"],
        parentId: null,
        conflicts: ["tragic-fate"],
        status: "active",
      },
      {
        id: "tragic-fate",
        name: "悲剧宿命",
        aliases: ["悲情", "宿命感"],
        parentId: null,
        conflicts: ["comedy-light"],
        status: "active",
      },
      {
        id: "romance-sweet",
        name: "甜宠浪漫",
        aliases: ["甜宠", "高糖"],
        parentId: null,
        conflicts: ["romance-angst"],
        status: "active",
      },
      {
        id: "romance-angst",
        name: "虐恋拉扯",
        aliases: ["虐恋", "情感拉扯"],
        parentId: null,
        conflicts: ["romance-sweet"],
        status: "active",
      },
      {
        id: "epic-majestic",
        name: "史诗宏大",
        aliases: ["史诗感", "宏大叙事"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "slice-calm",
        name: "日常平和",
        aliases: ["日常向", "平缓舒展"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "adrenaline",
        name: "高压肾上腺素",
        aliases: ["肾上腺素", "高强度刺激"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "nostalgic-melancholy",
        name: "怀旧惆怅",
        aliases: ["怀旧", "淡淡忧伤"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
    ],
    structure: [
      {
        id: "single-protagonist",
        name: "单主角主线",
        aliases: ["单线主角", "主角中心"],
        parentId: null,
        conflicts: ["ensemble-multi-line"],
        status: "active",
      },
      {
        id: "ensemble-multi-line",
        name: "群像多线",
        aliases: ["群像", "多主角"],
        parentId: null,
        conflicts: ["single-protagonist"],
        status: "active",
      },
      {
        id: "linear-chronological",
        name: "线性时序",
        aliases: ["顺叙", "时间线推进"],
        parentId: null,
        conflicts: ["nonlinear-time"],
        status: "active",
      },
      {
        id: "nonlinear-time",
        name: "非线性时序",
        aliases: ["倒叙", "插叙", "多时空切换"],
        parentId: null,
        conflicts: ["linear-chronological"],
        status: "active",
      },
      {
        id: "first-person",
        name: "第一人称",
        aliases: ["第一视角", "我视角"],
        parentId: null,
        conflicts: ["third-limited", "third-omniscient"],
        status: "active",
      },
      {
        id: "third-limited",
        name: "第三人称限知",
        aliases: ["限知视角", "贴近视角"],
        parentId: null,
        conflicts: ["first-person", "third-omniscient"],
        status: "active",
      },
      {
        id: "third-omniscient",
        name: "第三人称全知",
        aliases: ["全知视角", "上帝视角"],
        parentId: null,
        conflicts: ["first-person", "third-limited"],
        status: "active",
      },
      {
        id: "multi-pov",
        name: "多视角切换",
        aliases: ["多 POV", "多人称切换"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "case-of-week",
        name: "单元事件结构",
        aliases: ["单元剧", "单元案"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "long-arc",
        name: "长线主线结构",
        aliases: ["长弧线", "大主线"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "three-act",
        name: "三幕式结构",
        aliases: ["三幕", "经典三幕"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "multi-thread-weave",
        name: "多线程编织结构",
        aliases: ["多线并行", "线程编织"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
    ],
    market: [
      {
        id: "fast-paced",
        name: "快节奏",
        aliases: ["高速推进", "强推进"],
        parentId: null,
        conflicts: ["slow-burn"],
        status: "active",
      },
      {
        id: "slow-burn",
        name: "慢热铺陈",
        aliases: ["慢节奏", "细水长流"],
        parentId: null,
        conflicts: ["fast-paced"],
        status: "active",
      },
      {
        id: "high-hook",
        name: "强钩子开篇",
        aliases: ["高钩子", "开篇爆点"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "daily-serial",
        name: "日更连载友好",
        aliases: ["日更", "高频连载"],
        parentId: null,
        conflicts: ["short-complete"],
        status: "active",
      },
      {
        id: "short-complete",
        name: "短篇完结型",
        aliases: ["短篇", "短平快完结"],
        parentId: null,
        conflicts: ["daily-serial"],
        status: "active",
      },
      {
        id: "adaptation-ready",
        name: "影视改编潜力",
        aliases: ["改编向", "影视化潜力"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "cp-driven",
        name: "CP驱动",
        aliases: ["人物关系驱动", "嗑点驱动"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "worldbuilding-driven",
        name: "设定驱动",
        aliases: ["世界观驱动", "设定密度高"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "twist-dense",
        name: "反转密集",
        aliases: ["多反转", "反转流"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "comfort-read",
        name: "解压下饭",
        aliases: ["轻松下饭", "解压向"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "cliffhanger-heavy",
        name: "章节钩尾强",
        aliases: ["章尾钩子", "追更驱动"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "premium-subscription",
        name: "付费订阅友好",
        aliases: ["订阅友好", "商业化友好"],
        parentId: null,
        conflicts: [],
        status: "active",
      },
      {
        id: "paper-first",
        name: "纸书优先节奏",
        aliases: ["实体出版优先", "纸书节奏"],
        parentId: null,
        conflicts: [],
        status: "deprecated",
      },
    ],
  },
};
